"".main STEXT nosplit size=66 args=0x0 locals=0x20
	0x0000 00000 (main.go:4)	TEXT	"".main(SB), NOSPLIT, $32-0
	0x0000 00000 (main.go:4)	SUBQ	$32, SP
	0x0004 00004 (main.go:4)	MOVQ	BP, 24(SP)
	0x0009 00009 (main.go:4)	LEAQ	24(SP), BP
	0x000e 00014 (main.go:4)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x000e 00014 (main.go:4)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x000e 00014 (main.go:7)	MOVQ	$0, "".arr(SP)
	0x0016 00022 (main.go:7)	XORPS	X0, X0
	0x0019 00025 (main.go:7)	MOVUPS	X0, "".arr+8(SP)
	0x001e 00030 (main.go:7)	MOVQ	$1, "".arr(SP)
	0x0026 00038 (main.go:7)	MOVQ	$2, "".arr+8(SP)
	0x002f 00047 (main.go:7)	MOVQ	$3, "".arr+16(SP)
	0x0038 00056 (<unknown line number>)	MOVQ	24(SP), BP
	0x003d 00061 (<unknown line number>)	ADDQ	$32, SP
	0x0041 00065 (<unknown line number>)	RET
	0x0000 48 83 ec 20 48 89 6c 24 18 48 8d 6c 24 18 48 c7  H.. H.l$.H.l$.H.
	0x0010 04 24 00 00 00 00 0f 57 c0 0f 11 44 24 08 48 c7  .$.....W...D$.H.
	0x0020 04 24 01 00 00 00 48 c7 44 24 08 02 00 00 00 48  .$....H.D$.....H
	0x0030 c7 44 24 10 03 00 00 00 48 8b 6c 24 18 48 83 c4  .D$.....H.l$.H..
	0x0040 20 c3                                             .
"".t STEXT nosplit size=1 args=0x40 locals=0x0
	0x0000 00000 (main.go:12)	TEXT	"".t(SB), NOSPLIT, $0-64
	0x0000 00000 (main.go:12)	FUNCDATA	$0, gclocals·1d0ed49f611d7e40a62328b5976a2ede(SB)
	0x0000 00000 (main.go:12)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (main.go:14)	RET
	0x0000 c3                                               .
"".init STEXT size=86 args=0x0 locals=0x8
	0x0000 00000 (<autogenerated>:1)	TEXT	"".init(SB), $8-0
	0x0000 00000 (<autogenerated>:1)	MOVQ	TLS, CX
	0x0009 00009 (<autogenerated>:1)	MOVQ	(CX)(TLS*2), CX
	0x0010 00016 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x0014 00020 (<autogenerated>:1)	JLS	79
	0x0016 00022 (<autogenerated>:1)	SUBQ	$8, SP
	0x001a 00026 (<autogenerated>:1)	MOVQ	BP, (SP)
	0x001e 00030 (<autogenerated>:1)	LEAQ	(SP), BP
	0x0022 00034 (<autogenerated>:1)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0022 00034 (<autogenerated>:1)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0022 00034 (<autogenerated>:1)	MOVBLZX	"".initdone·(SB), AX
	0x0029 00041 (<autogenerated>:1)	CMPB	AL, $1
	0x002b 00043 (<autogenerated>:1)	JLS	54
	0x002d 00045 (<autogenerated>:1)	MOVQ	(SP), BP
	0x0031 00049 (<autogenerated>:1)	ADDQ	$8, SP
	0x0035 00053 (<autogenerated>:1)	RET
	0x0036 00054 (<autogenerated>:1)	JNE	63
	0x0038 00056 (<autogenerated>:1)	PCDATA	$0, $0
	0x0038 00056 (<autogenerated>:1)	CALL	runtime.throwinit(SB)
	0x003d 00061 (<autogenerated>:1)	UNDEF
	0x003f 00063 (<autogenerated>:1)	MOVB	$2, "".initdone·(SB)
	0x0046 00070 (<autogenerated>:1)	MOVQ	(SP), BP
	0x004a 00074 (<autogenerated>:1)	ADDQ	$8, SP
	0x004e 00078 (<autogenerated>:1)	RET
	0x004f 00079 (<autogenerated>:1)	NOP
	0x004f 00079 (<autogenerated>:1)	PCDATA	$0, $-1
	0x004f 00079 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x0054 00084 (<autogenerated>:1)	JMP	0
	0x0000 65 48 8b 0c 25 28 00 00 00 48 8b 89 00 00 00 00  eH..%(...H......
	0x0010 48 3b 61 10 76 39 48 83 ec 08 48 89 2c 24 48 8d  H;a.v9H...H.,$H.
	0x0020 2c 24 0f b6 05 00 00 00 00 3c 01 76 09 48 8b 2c  ,$.......<.v.H.,
	0x0030 24 48 83 c4 08 c3 75 07 e8 00 00 00 00 0f 0b c6  $H....u.........
	0x0040 05 00 00 00 00 02 48 8b 2c 24 48 83 c4 08 c3 e8  ......H.,$H.....
	0x0050 00 00 00 00 eb aa                                ......
	rel 12+4 t=16 TLS+0
	rel 37+4 t=15 "".initdone·+0
	rel 57+4 t=8 runtime.throwinit+0
	rel 65+4 t=15 "".initdone·+-1
	rel 80+4 t=8 runtime.morestack_noctxt+0
go.info."".t$abstract SDWARFINFO dupok size=45
	0x0000 03 2e 74 00 01 01 10 61 72 72 00 00 00 00 00 00  ..t....arr......
	0x0010 10 69 00 00 00 00 00 00 10 70 00 00 00 00 00 00  .i.......p......
	0x0020 10 73 6c 69 63 65 00 00 00 00 00 00 00           .slice.......
	rel 12+4 t=28 go.info.[3]int+0
	rel 20+4 t=28 go.info.int+0
	rel 28+4 t=28 go.info.*int+0
	rel 40+4 t=28 go.info.[]int+0
go.info."".main SDWARFINFO size=46
	0x0000 02 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 09 61 72 72 00 07 00 00 00 00 02 91 58 00        .arr........X.
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+66
	rel 27+4 t=29 gofile..E:\GoProject\src\project\hello\asm\main.go+0
	rel 38+4 t=28 go.info.[3]int+0
go.range."".main SDWARFRANGE size=0
go.info."".t SDWARFINFO size=55
	0x0000 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 01 9c 11 00 00 00 00 02 91 10 11  ................
	0x0020 00 00 00 00 01 9c 11 00 00 00 00 02 91 08 11 00  ................
	0x0030 00 00 00 02 91 28 00                             .....(.
	rel 1+4 t=28 go.info."".t$abstract+0
	rel 5+8 t=1 "".t+0
	rel 13+8 t=1 "".t+1
	rel 24+4 t=28 go.info."".t$abstract+6
	rel 32+4 t=28 go.info."".t$abstract+16
	rel 39+4 t=28 go.info."".t$abstract+24
	rel 47+4 t=28 go.info."".t$abstract+32
go.range."".t SDWARFRANGE size=0
go.info."".init SDWARFINFO size=33
	0x0000 02 22 22 2e 69 6e 69 74 00 00 00 00 00 00 00 00  ."".init........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 00                                               .
	rel 9+8 t=1 "".init+0
	rel 17+8 t=1 "".init+86
	rel 27+4 t=29 gofile..<autogenerated>+0
go.range."".init SDWARFRANGE size=0
"".statictmp_0 SRODATA size=24
	0x0000 01 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
	0x0010 03 00 00 00 00 00 00 00                          ........
"".initdone· SNOPTRBSS size=1
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*[]int- SRODATA dupok size=9
	0x0000 00 00 06 2a 5b 5d 69 6e 74                       ...*[]int
type.*[]int SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 1b 31 52 88 00 08 08 36 00 00 00 00 00 00 00 00  .1R....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]int-+0
	rel 48+8 t=1 type.[]int+0
type.[]int SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 8e 66 f9 1b 02 08 08 17 00 00 00 00 00 00 00 00  .f..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]int-+0
	rel 44+4 t=6 type.*[]int+0
	rel 48+8 t=1 type.int+0
type..hashfunc24 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 18 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 runtime.memhash_varlen+0
type..eqfunc24 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 18 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 runtime.memequal_varlen+0
type..alg24 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 type..hashfunc24+0
	rel 8+8 t=1 type..eqfunc24+0
type..namedata.*[3]int- SRODATA dupok size=10
	0x0000 00 00 07 2a 5b 33 5d 69 6e 74                    ...*[3]int
type.*[3]int SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 25 30 9a e3 00 08 08 36 00 00 00 00 00 00 00 00  %0.....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[3]int-+0
	rel 48+8 t=1 type.[3]int+0
runtime.gcbits. SRODATA dupok size=0
type.[3]int SRODATA dupok size=72
	0x0000 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 63 c4 1a 46 02 08 08 91 00 00 00 00 00 00 00 00  c..F............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 03 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 type..alg24+0
	rel 32+8 t=1 runtime.gcbits.+0
	rel 40+4 t=5 type..namedata.*[3]int-+0
	rel 44+4 t=6 type.*[3]int+0
	rel 48+8 t=1 type.int+0
	rel 56+8 t=1 type.[]int+0
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·1d0ed49f611d7e40a62328b5976a2ede SRODATA dupok size=9
	0x0000 01 00 00 00 08 00 00 00 00                       .........
